#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $HUNTERX_REPO == "hunterX" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $HUNTERX_REPO == "HUNTERX" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $HUNTERX_REPO =~ $regex ]]
    then
        if [[ $HUNTERX_REPO_BRANCH ]]
        then
            echo "${HUNTERX_REPO}/archive/${HUNTERX_REPO_BRANCH}.zip"
        else
            echo "${HUNTERX_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="hunterX.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HUNTERXPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $HUNTERXPATH
    echo "    Starting HunterX    "
    echo "
    __ ____  ___  _______________  _  __
  / // / / / / |/ /_  __/ __/ _ \| |/_/
 / _  / /_/ /    / / / / _// , _/>  <  
/_//_/\____/_/|_/ /_/ /___/_/|_/_/|_|  
                                        
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
